### PR TITLE
Update to latest version of Backstage

### LINKED ISSUE #29: Running with the latest version of Backstage results in an error
When attempting to run on Backstage version 1.17.5, the following error occurs:

```
[1] Backend failed to start up, Error: Invalid configuration schema in ..\..\node_modules\@parfuemerie-douglas\scaffolder-backend-module-azure-pipelines\node_modules\@backstage\plugin-scaffolder-backend\node_modules\@backstage\backend-common\config.d.ts, the following definitions are not supported:    
[1]
[1]   Partial<{[key:string]:unknown;password:string;}>
```

I believe this can be solved by updating to the latest version of Backstage and publishing a new version of the package.

### PR DESCRIPTION
**Pull request by arhill05**
Resolve #29

### CODE REVIEW

**Comment by arhill05** [comment]
@antoniobergas could we see about merging this and publishing a new version? We'd like to update to the latest version of Backstage and this is preventing us from doing so.

**Comment by antoniobergas** [comment]
Hi @arhill05 , I agree to update to the latest version but I don't have permissions to merge PRs. 

Maybe @hevans-dglcom can give you a hand?

**Comment by arhill05** [comment]
@hevans-dglcom any chance you could take a look at this and publish a new version of this package? This is blocking my teams from upgrading to newer versions and we may have to stop using this package :(

**Comment by antoniobergas** [comment]
Hi @arhill05 , I would say we are pending to hear from the maintainers about this https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/30

After a decision on it, will probably need to re-update again and also change some breaking changes from the plugins

**Comment by antoniobergas** [comment]
https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/30#issuecomment-1762015990

**Comment by Tushti02** [comment]
@hevans-dglcom @antoniobergas  do we have any update on this as createAzurePipelineAction now fails with latest version upgrade of  "@backstage/integration": "^1.6.2"

**Comment by Tushti02** [comment]
@antoniobergas  This is sad :( Can you suggest some for azure devops scaffolder pipeline create and run?

**Comment by antoniobergas** [comment]
AFAIK there's no other azdops public plugin 🥲 for the scaffolder.

**Pull request closed without merging**
